# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('xml_file_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=30)),
                ('speech', models.CharField(choices=[('N', 'Substantiv'), ('V', 'Verben'), ('A', 'Adjektiv')], default='N', max_length=1)),
                ('chinese', models.CharField(max_length=20)),
                ('picture', models.CharField(blank=True, max_length=30, null=True)),
                ('audio', models.CharField(blank=True, max_length=30, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
