# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:35
from __future__ import unicode_literals

from django.db import migrations,models
from lxml import etree
def add_word(apps,schema_editor):
    Word=apps.get_model("DeutschLernen","Word")
    f=open('E:/DeutschLernen/Deutsch-Lernen/Deutsch-Lernen/Wordlist_11.xml','rb')
    root=etree.fromstring(f.read())
    i=0
    while(i<464):
        f=open('E:/DeutschLernen/Deutsch-Lernen/Deutsch-Lernen/Wort/%d.xml'%i,'rb')
        st=f.read().decode('utf-8')
        u=Word()
        u.entry=root[i].text
        u.chinese=root[i].get('chinese')
        u.xml=st
        u.xml_file_name='N'+str(i+1)+'.xml'
        u.save()
        i=i+1


class Migration(migrations.Migration):

    dependencies = [
        ('DeutschLernen', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_word)
    ]
