# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 11:20
from __future__ import unicode_literals
a=[['home','首页'],['word_search','单词查询'],['text_view','课文浏览'],['word_test','单词测试'],
   ['about_us','关于我们']]
from django.db import migrations, models
def add_website_text(apps,schema_editor):
    Text=apps.get_model("DeutschLernen","Website_Text")
    for i in a:
        u=Text(key=i[0],chinese=i[1])
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('DeutschLernen', '0002_auto_20170403_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Text',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('chinese', models.CharField(max_length=200)),
            ],
        ),migrations.RunPython(add_website_text)
    ]
