# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeutschLernen', '0004_auto_20170403_1938'),
        ('DeutschLernen', '0003_website_text'),
    ]

    operations = [
    ]
