# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 18:31
from __future__ import unicode_literals

from django.db import migrations
from lxml import etree

def add_einheit(apps,schema_editor):
    Word=apps.get_model("DeutschLernen","Word")
    i=1
    while(i<465):
        f=open('E:/DeutschLernen/Deutsch-Lernen/Deutsch-Lernen/Wort/%d.xml'%i,'rb')
        st=f.read()
        root=etree.fromstring(st)
        u=Word.objects.get(xml_file_name='N'+str(i)+'.xml')
        u.einheit=int(root[1].text)
        u.save()
        i=i+1

class Migration(migrations.Migration):

    dependencies = [
        ('DeutschLernen', '0006_auto_20170404_0208'),
    ]

    operations = [
        migrations.RunPython(add_einheit)
    ]
