# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeutschLernen', '0007_auto_20170404_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='anteil',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Intentionen'), ('L', 'Leseverstehen'), ('E', 'Einführung'), ('U', 'Übungen'), ('H', 'Hörverstehen'), ('O', 'Others')], default='T', max_length=1),
        ),
    ]
